name: Poop
version: 2.0.0
description: Players can now poop
author: norway240
website: http://dev.bukkit.org/bukkit-plugins/poop-plugin/
main: com.norway240.poop.Poop

commands:
   poop:
      description: Allows the player to poop
      usage: /poop
      permission: poop

permissions:
    poop:
        description: Allows the player to poop
        default: true