name: Poop
version: 2.0.0
description: Players can now poop
author: norway240
website: http://dev.bukkit.org/bukkit-plugins/poop-plugin/
main: com.norway240.poop.Poop

commands:
   poop:
      description: Does things
      usage: /poop [info, version, update]
      permission: poop

permissions:
    poop:
        description: Does things
        default: true